FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    xorriso \
    libarchive-tools \
    squashfs-tools \
    curl \
    wget \
    ca-certificates \
    rsync \
    xz-utils \
    sudo \
    git \
    live-build \
    debootstrap \
    dosfstools \
    mtools \
    grub-pc-bin \
    grub-efi-amd64-bin \
    isolinux \
    syslinux-common \
    memtest86+ \
    apt-utils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
