#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
LAYOUT_DIR="$ROOT_DIR/kismet-build/dev-preview-layout"

mkdir -p "$LAYOUT_DIR/filesystem/usr/local/bin"
mkdir -p "$LAYOUT_DIR/filesystem/usr/local/lib/kismet"
mkdir -p "$LAYOUT_DIR/filesystem/etc/systemd/system"
mkdir -p "$LAYOUT_DIR/filesystem/etc/skel/.config/kismet"
mkdir -p "$LAYOUT_DIR/filesystem/etc/skel/.config/autostart"
mkdir -p "$LAYOUT_DIR/filesystem/etc/skel/.config/gtk-3.0"
mkdir -p "$LAYOUT_DIR/filesystem/etc/skel/.config"
mkdir -p "$LAYOUT_DIR/filesystem/etc/skel/.local/share/applications"
mkdir -p "$LAYOUT_DIR/filesystem/etc/kismet"
mkdir -p "$LAYOUT_DIR/filesystem/usr/share/plymouth/themes/kismet"
mkdir -p "$LAYOUT_DIR/filesystem/usr/share/backgrounds/kismet"
mkdir -p "$LAYOUT_DIR/filesystem/usr/share/sddm/themes/kismet"
mkdir -p "$LAYOUT_DIR/filesystem/usr/share/icons/hicolor/scalable/apps"
mkdir -p "$LAYOUT_DIR/filesystem/usr/share/icons/hicolor/256x256/apps"
mkdir -p "$LAYOUT_DIR/filesystem/usr/share/themes"
mkdir -p "$LAYOUT_DIR/filesystem/usr/share/gnome-shell/extensions"
mkdir -p "$LAYOUT_DIR/filesystem/etc/openclaw"

cp -f "$ROOT_DIR/kismet-base/config/usr/local/bin/kismet-firstboot" "$LAYOUT_DIR/filesystem/usr/local/bin/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/bin/kismet-firstboot-wizard" "$LAYOUT_DIR/filesystem/usr/local/bin/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/bin/kismet-ctl" "$LAYOUT_DIR/filesystem/usr/local/bin/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/bin/kismet-ollama-loader" "$LAYOUT_DIR/filesystem/usr/local/bin/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/bin/kismet-ai-center" "$LAYOUT_DIR/filesystem/usr/local/bin/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/bin/kismet-ai-launch" "$LAYOUT_DIR/filesystem/usr/local/bin/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/bin/kismet-ai-bootstrap" "$LAYOUT_DIR/filesystem/usr/local/bin/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/bin/kismet-plasma-polish" "$LAYOUT_DIR/filesystem/usr/local/bin/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/bin/kismet-run-exe" "$LAYOUT_DIR/filesystem/usr/local/bin/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/bin/kismet" "$LAYOUT_DIR/filesystem/usr/local/bin/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/bin/kismet-gnome-polish" "$LAYOUT_DIR/filesystem/usr/local/bin/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/bin/kismet-extra-polish" "$LAYOUT_DIR/filesystem/usr/local/bin/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/bin/kismet-install-openbar" "$LAYOUT_DIR/filesystem/usr/local/bin/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/bin/kismet-game-library" "$LAYOUT_DIR/filesystem/usr/local/bin/"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/bin/kismet"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/bin/kismet-gnome-polish"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/bin/kismet-extra-polish"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/bin/kismet-install-openbar"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/bin/kismet-game-library"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/lib/kismet/kismet_agent.py" "$LAYOUT_DIR/filesystem/usr/local/lib/kismet/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/lib/kismet/habit_tracker.py" "$LAYOUT_DIR/filesystem/usr/local/lib/kismet/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/lib/kismet/hw_monitor.py" "$LAYOUT_DIR/filesystem/usr/local/lib/kismet/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/lib/kismet/scheduler.py" "$LAYOUT_DIR/filesystem/usr/local/lib/kismet/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/lib/kismet/ollama_bridge.py" "$LAYOUT_DIR/filesystem/usr/local/lib/kismet/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/lib/kismet/kismet_agent_runner.py" "$LAYOUT_DIR/filesystem/usr/local/lib/kismet/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/lib/kismet/kismet-firstboot-wizard" "$LAYOUT_DIR/filesystem/usr/local/lib/kismet/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/lib/kismet/kismet-ctl" "$LAYOUT_DIR/filesystem/usr/local/lib/kismet/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/lib/kismet/model-loader.sh" "$LAYOUT_DIR/filesystem/usr/local/lib/kismet/"
cp -f "$ROOT_DIR/kismet-base/config/usr/local/lib/kismet/kismet-ai-center" "$LAYOUT_DIR/filesystem/usr/local/lib/kismet/"
cp -f "$ROOT_DIR/kismet-base/config/etc/systemd/system/kismet-firstboot.service" "$LAYOUT_DIR/filesystem/etc/systemd/system/"
cp -f "$ROOT_DIR/kismet-base/config/etc/systemd/system/kismet-agent.service" "$LAYOUT_DIR/filesystem/etc/systemd/system/"
cp -f "$ROOT_DIR/kismet-base/config/etc/systemd/system/kismet-ollama-loader.service" "$LAYOUT_DIR/filesystem/etc/systemd/system/"
cp -f "$ROOT_DIR/kismet-base/config/etc/systemd/system/kismet-ollama-bridge.service" "$LAYOUT_DIR/filesystem/etc/systemd/system/"
cp -f "$ROOT_DIR/kismet-base/config/etc/kismet/models.env" "$LAYOUT_DIR/filesystem/etc/kismet/"
cp -f "$ROOT_DIR/kismet-base/config/etc/kismet/ai-stack.json" "$LAYOUT_DIR/filesystem/etc/kismet/"
cp -f "$ROOT_DIR/kismet-base/config/skel/.config/kismet/kismet.conf" "$LAYOUT_DIR/filesystem/etc/skel/.config/kismet/"
cp -f "$ROOT_DIR/kismet-base/config/skel/.config/kismet/desktop-defaults.md" "$LAYOUT_DIR/filesystem/etc/skel/.config/kismet/"
cp -f "$ROOT_DIR/kismet-base/config/skel/.config/kdeglobals" "$LAYOUT_DIR/filesystem/etc/skel/.config/"
cp -f "$ROOT_DIR/kismet-base/config/skel/.config/konsolerc" "$LAYOUT_DIR/filesystem/etc/skel/.config/"
cp -f "$ROOT_DIR/kismet-base/config/skel/.config/autostart/kismet-plasma-polish.desktop" "$LAYOUT_DIR/filesystem/etc/skel/.config/autostart/"
cp -f "$ROOT_DIR/kismet-base/config/skel/.config/autostart/kismet-gnome-polish.desktop" "$LAYOUT_DIR/filesystem/etc/skel/.config/autostart/"
cp -f "$ROOT_DIR/kismet-base/config/skel/.config/autostart/kismet-extra-polish.desktop" "$LAYOUT_DIR/filesystem/etc/skel/.config/autostart/"
cp -f "$ROOT_DIR/kismet-base/config/skel/.config/gtk-3.0/settings.ini" "$LAYOUT_DIR/filesystem/etc/skel/.config/gtk-3.0/"
cp -f "$ROOT_DIR/kismet-base/config/skel/.local/share/applications/kismet-ai-center.desktop" "$LAYOUT_DIR/filesystem/etc/skel/.local/share/applications/"
cp -f "$ROOT_DIR/kismet-base/config/skel/.local/share/applications/kismet-hermes.desktop" "$LAYOUT_DIR/filesystem/etc/skel/.local/share/applications/"
cp -f "$ROOT_DIR/kismet-base/config/skel/.local/share/applications/kismet-opencode.desktop" "$LAYOUT_DIR/filesystem/etc/skel/.local/share/applications/"
cp -f "$ROOT_DIR/kismet-base/config/skel/.local/share/applications/kismet-run-exe.desktop" "$LAYOUT_DIR/filesystem/etc/skel/.local/share/applications/"
cp -f "$ROOT_DIR/kismet-base/config/skel/.local/share/applications/kismet-game-library.desktop" "$LAYOUT_DIR/filesystem/etc/skel/.local/share/applications/"
cp -f "$ROOT_DIR/kismet-base/config/skel/.local/share/applications/kismet-mines.desktop" "$LAYOUT_DIR/filesystem/etc/skel/.local/share/applications/"
cp -f "$ROOT_DIR/kismet-base/config/skel/.local/share/applications/kismet-chess.desktop" "$LAYOUT_DIR/filesystem/etc/skel/.local/share/applications/"
cp -f "$ROOT_DIR/kismet-base/config/skel/.local/share/applications/kismet-sudoku.desktop" "$LAYOUT_DIR/filesystem/etc/skel/.local/share/applications/"
cp -f "$ROOT_DIR/kismet-base/config/skel/.local/share/applications/kismet.desktop" "$LAYOUT_DIR/filesystem/etc/skel/.local/share/applications/"
cp -f "$ROOT_DIR/kismet-base/config/skel/.zshrc" "$LAYOUT_DIR/filesystem/etc/skel/"
cp -f "$ROOT_DIR/kismet-theme/plymouth/kismet.plymouth" "$LAYOUT_DIR/filesystem/usr/share/plymouth/themes/kismet/"
cp -f "$ROOT_DIR/kismet-theme/plymouth/kismet.script" "$LAYOUT_DIR/filesystem/usr/share/plymouth/themes/kismet/"
cp -f "$ROOT_DIR/kismet-theme/sddm/theme.conf.user" "$LAYOUT_DIR/filesystem/usr/share/sddm/themes/kismet/"
for icon in "$ROOT_DIR"/kismet-theme/icons/*.svg; do
  [ -f "$icon" ] || continue
  cp -f "$icon" "$LAYOUT_DIR/filesystem/usr/share/icons/hicolor/scalable/apps/"
done
for wallpaper in "$ROOT_DIR"/kismet-theme/wallpapers/*; do
  [ -f "$wallpaper" ] || continue
  cp -f "$wallpaper" "$LAYOUT_DIR/filesystem/usr/share/backgrounds/kismet/"
done

if [ -d "$ROOT_DIR/kismet-theme/vendor/catppuccin-tmp/catppuccin-mocha-blue-standard+default" ]; then
  rm -rf "$LAYOUT_DIR/filesystem/usr/share/themes/catppuccin-mocha-blue-standard+default"
  cp -a "$ROOT_DIR/kismet-theme/vendor/catppuccin-tmp/catppuccin-mocha-blue-standard+default" \
    "$LAYOUT_DIR/filesystem/usr/share/themes/"
fi

if [ -d "$ROOT_DIR/kismet-theme/vendor/openbar-tmp/openbar@neuromorph" ]; then
  rm -rf "$LAYOUT_DIR/filesystem/usr/share/gnome-shell/extensions/openbar@neuromorph"
  cp -a "$ROOT_DIR/kismet-theme/vendor/openbar-tmp/openbar@neuromorph" \
    "$LAYOUT_DIR/filesystem/usr/share/gnome-shell/extensions/"
fi

chmod +x "$LAYOUT_DIR/filesystem/usr/local/bin/kismet-firstboot"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/bin/kismet-firstboot-wizard"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/bin/kismet-ctl"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/bin/kismet-ollama-loader"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/bin/kismet-ai-center"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/bin/kismet-ai-launch"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/bin/kismet-ai-bootstrap"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/bin/kismet-plasma-polish"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/bin/kismet-run-exe"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/bin/kismet-extra-polish"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/bin/kismet-install-openbar"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/lib/kismet/kismet_agent.py"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/lib/kismet/habit_tracker.py"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/lib/kismet/hw_monitor.py"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/lib/kismet/scheduler.py"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/lib/kismet/ollama_bridge.py"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/lib/kismet/kismet_agent_runner.py"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/lib/kismet/kismet-firstboot-wizard"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/lib/kismet/kismet-ctl"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/lib/kismet/model-loader.sh"
chmod +x "$LAYOUT_DIR/filesystem/usr/local/lib/kismet/kismet-ai-center"

echo "==> Dev preview filesystem layout prepared at $LAYOUT_DIR"
